name: Benchmark multiple commits

on:
  workflow_call:
    inputs:
      commit_ids:
        description: "JSON array of commit SHAs to benchmark"
        required: true
        type: string   # JSON array passed as a string
    outputs:
      results_dir_root:
        description: "Root folder that now contains results/<sha>/..."
        value: ${{ jobs.bench.outputs.results_root }}

jobs:
  bench:
    runs-on: ubuntu-latest
    outputs:
      results_root: ${{ steps.set-root.outputs.root }}

    steps:
      - name: Set root output
        id: set-root
        run: echo "root=$(pwd)/results" >> "$GITHUB_OUTPUT"

      - name: Install tooling
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Loop & benchmark
        env:
          COMMITS_JSON: ${{ inputs.commit_ids }}
        run: |
          echo "===== BENCHMARKING ${{ env.COMMITS_JSON }} ====="

          # -- run benchmark
          python benchmark.py \
            --commit ${{ inputs.commit_ids }} \
            --config ./configs/benchmark-configs.json

