name: Valkey Benchmark CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  determine_commits:
    uses: ./.github/workflows/determine_commits.yml
    with:
      branch: unstable
      max_commits: 3
    secrets: inherit

  benchmark_commits:
    needs: determine_commits
    if: ${{ fromJson(needs.determine_commits.outputs.commit_ids) != [] }}
    uses: ./.github/workflows/benchmark_commits.yml
    with:
      commit_ids: ${{ needs.determine_commits.outputs.commit_ids }}
    secrets: inherit

  upload_results:
    needs: benchmark_commits
    uses: ./.github/workflows/upload_results.yml
    with:
      commit_ids:       ${{ needs.determine_commits.outputs.commit_ids }}
      results_dir_root: ${{ needs.benchmark_commits.outputs.results_dir_root }}
    secrets: inherit
